# Generated by Django 5.0.6 on 2024-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalduApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', ''), ('S', 'Самотній/Самотня'), ('M', 'Одружений/Заміжня'), ('D', 'Розлучений/Розлучена'), ('W', 'Вдівець/Вдова')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('', ''), ('M', 'Чоловічий'), ('F', 'Жіночий')], max_length=10),
        ),
    ]
