# Generated by Django 5.0.6 on 2024-05-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BalduApp', '0002_user_marital_status_user_orientation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
